enableConstraintsChecks: true

enableHardenedMode: true

enableInlineHunks: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

# Peer dependency resolution
peerDependencyMode: loose

# Allow peer dependency warnings without failing
enableStrictSsl: false
